### ISSUE TITLE
Does this work with flutter ?

### ISSUE THREAD

**Issue by naveenbharadwaj19** [alexmamo/FirestoreDocument-Android#6]
I implemented this as mentioned in the description but i cannot add `FirestoreDocument firestoreDocument = FirestoreDocument.getInstance();` Why ?

`project build.gradle`
```
allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://jitpack.io'
        }
    }
}
```

`app<level> build.gradle`
```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:26.2.0')
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.google.firebase:firebase-analytics:18.0.0'
    implementation 'com.github.alexmamo:FirestoreDocument-Android:0.1.5'
}
```

**Comment by alexmamo** [comment]
I didn't try to use it on Flutter, so I can't say it's working or not. However, FirestoreDocument firestoreDocument = FirestoreDocument.getInstance(); it's Java code and I'm afraid it's not working the same way in Flutter.

**Comment by naveenbharadwaj19** [comment]
I think there is no API or firestore attributes to get the size of document (Mb)

**Comment by alexmamo** [comment]
Yes, that's why I've created this library. I'm sorry if it doesn't work on Flutter.

**Comment by naveenbharadwaj19** [comment]
Did i miss any piece of code or made any mistake ? in dart we can call firestore instance 
`DocumentReference callInstance = FirebaseFirestore.instance.doc('documentPath');`

**Comment by alexmamo** [comment]
So it doesn't work either using that code?

**Comment by naveenbharadwaj19** [comment]
Yes .There is no method called `getSize()`. But there is an option called size it returns no of documents not the size of document

**Comment by alexmamo** [comment]
Yes, I know that option but doesn't return the size of the document. That's the reason why I have created this library.

**Comment by naveenbharadwaj19** [comment]
So there is no way to get the size of the document in flutter ?

**Comment by alexmamo** [comment]
I really don't know, as I didn't try that.
