### ISSUE TITLE
its urgent 

### ISSUE THREAD

**Issue by Bhumesh-45678** [alexmamo/FirestoreDocument-Android#7]
Respected Sir... i am new to android studio. i am add FirestoreDocument-Android library but in my main activity java class , FirestoreDocument gives error  like make a create FirestoreDocument class again. please help me sir. please detail for adding your library and how to use. please i am needy.

public class MainActivity extends AppCompatActivity {
    FirebaseFirestore db;
    //FirestoreDocument firestoreDocument ;
DocumentSnapshot documentSnapshot;

    public FirestoreDocument firestoreDocument;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        db = FirebaseFirestore.getInstance();

       // FirestoreDocument firestoreDocument;
        firestoreDocument = FirestoreDocument.getInstance();

        int documentSize = firestoreDocument.getSize(documentSnapshot);
        FirebaseFirestore rootRef = FirebaseFirestore.getInstance();
        DocumentReference myTaskIdRef = rootRef.collection("users").document("jeff").collection("tasks").document("my_task_id");

        myTaskIdRef.get().addOnCompleteListener(task -> {
            if (task.isSuccessful()) {
                DocumentSnapshot document = task.getResult();
                if (document.exists()) {
                   int  documentSize1= firestoreDocument.getSize(document);
                    Log.d("TAG", "documentSize: " + documentSize1);
                }
            }
        });

    }
}

**Comment by alexmamo** [comment]
It should be int  **documentSize1= document.getSize(document);** and not int  documentSize1= firestoreDocument.getSize(document);, right?

**Comment by Bhumesh-45678** [comment]
![image](https://user-images.githubusercontent.com/103883885/163712938-a06a7b50-4fd4-4b15-b2fa-80471de30f1c.png)

**Comment by Bhumesh-45678** [comment]
sir please check my code FirestoreDocument get error above in pic

**Comment by alexmamo** [comment]
Check [this](https://github.com/alexmamo/FirestoreDocument-Android/blob/master/app/src/main/java/ro/alexmamo/firestoredocumentsize/MainActivity.java) out and tell me if it works. If it does, please close the issue. Thanks.

**Comment by Bhumesh-45678** [comment]
not sir. same errors ... sir i think i am not correctly added the your  library in my project. can you detailed explanation how to add it

**Comment by alexmamo** [comment]
Have you tried to follow [these steps correctly](https://github.com/alexmamo/FirestoreDocument-Android/tree/master/firestore-document)?

**Comment by Bhumesh-45678** [comment]
![image](https://user-images.githubusercontent.com/103883885/163730256-c6a15008-e7c6-4e06-94c4-d78191eff858.png)






when i add manually .... there is no repository ..... this is problem with my application.....please find the solution

**Comment by alexmamo** [comment]
I don't see any reason why it behaves like that, I just tested with the dependencies added directly in the Gradle file and it works perfectly fine.

**Comment by Bhumesh-45678** [comment]
Solved sir ........thanks for this library.
the main problem is when i added the following code in project build.gradle (project)
allprojects {
    repositories {
    
        maven {
            url 'https://jitpack.io'
        }
    }
}
it will not work for my new android studio version
when i also added to settings.gradle . it works fine....so i am very happy . really thanks sir for this library and quick response.
